name: flutter_boilerplate_bloc
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_core: ^2.24.2
  flutter_bloc: ^8.1.3
  http: ^1.1.2
  equatable: ^2.0.5
  lottie: ^3.0.0
  provider: ^6.1.1
  dartz: ^0.10.1
  top_snackbar_flutter: ^3.1.0
  cloud_firestore: ^4.14.0
  either_dart: ^1.0.0
  firebase_auth: ^4.16.0
  font_awesome_flutter: ^10.6.0
  package_info_plus: ^5.0.1
  flutter_secure_storage: ^9.0.0
  flutter_carousel_widget: ^2.2.0
  shared_preferences: ^2.2.2
  dropdown_textfield: ^1.0.8
  firebase_analytics: ^10.8.0
  flutter_easyloading: ^3.0.5
  easy_localization: ^3.0.1
  flutter_flavor: ^3.1.3
  firebase_crashlytics: ^3.4.9
  injector: ^3.0.0
  uuid: ^4.3.3
  get_it: ^7.6.7
  logger: ^2.0.2+1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Light.ttf
          weight: 100
